[package]
name = "sql-gui-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
baibai-core = { path = "../../core" }
async-trait = "0.1"
rusqlite = { version = "0.29", features = ["bundled"] }
tokio = { version = "1.0", features = ["full"] } 